In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Loading the dataset
df = pd.read_csv("../data/transactions.csv")

In [3]:
df.head()

         Date Description       Category  Amount    Type
0  2026-05-01      Zomato           Food     450   Debit
1  2026-05-01      Salary         Income   50000  Credit
2  2026-05-02        Uber         Travel     220   Debit
3  2026-05-03      Amazon       Shopping    1999   Debit
4  2026-05-04     Netflix  Entertainment     649   Debit

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         10 non-null     str
 1   Description  10 non-null     str
 2   Category     10 non-null     str
 3   Amount       10 non-null     int64
 4   Type         10 non-null     str
dtypes: int64(1), str(4)
memory usage: 532.0 bytes

In [7]:
df.describe()

             Amount
count     10.000000
mean    6973.700000
std    15522.650068
min      220.000000
25%      499.750000
50%     1149.500000
75%     1949.250000
max    50000.000000

In [8]:
df["Amount"]

0      450
1    50000
2      220
3     1999
4      649
5      320
6     1800
7    12000
8      799
9     1500
Name: Amount, dtype: int64

In [9]:
type(df["Amount"])

pandas.Series

In [10]:
df[["Date", "Amount"]]

         Date  Amount
0  2026-05-01     450
1  2026-05-01   50000
2  2026-05-02     220
3  2026-05-03    1999
4  2026-05-04     649
5  2026-05-05     320
6  2026-05-06    1800
7  2026-05-07   12000
8  2026-05-08     799
9  2026-05-09    1500